<?php

namespace gordian\reefknot\input\validate;

require_once dirname (__FILE__) . '/../../../input/validate/DataSetGlobalized.php';

/**
 * Test class for DataSetGlobalized.
 * Generated by PHPUnit on 2012-03-28 at 17:05:49.
 */
class DataSetGlobalizedTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var gordian\reefknot\input\validate\DataSetGlobalized
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new DataSetGlobalized ($this -> getMock ('gordian\reefknot\input\validate\type\IsArray'));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 */
	public function testGetGlobalInvalids ()
	{
		$this -> assertEquals ($this -> object -> getGlobalInvalids (), array ());
	}

	/**
	 */
	public function testResetInvalids ()
	{
		$this -> object -> resetInvalids ();
		$this -> assertEquals ($this -> object -> getInvalids (), array ());
		$this -> assertEquals ($this -> object -> getGlobalInvalids (), array ());
	}

	/**
	 */
	public function testHasInvalids ()
	{
		$this -> assertFalse ($this -> object -> hasInvalids ());
	}

	/**
	 */
	public function testAddGlobalProp ()
	{
		$prop	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Prop');
		$this -> assertFalse (in_array ($prop, $this -> object -> getGlobalProps (), true));
		$this -> object -> addGlobalProp ($prop);
		$this -> assertTrue (in_array ($prop, $this -> object -> getGlobalProps (), true));
	}

	public function testAddSameGlobalPropThrowsException ()
	{
		$exception	= NULL;
		$prop	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Prop');
		$this -> assertFalse (in_array ($prop, $this -> object -> getGlobalProps (), true));
		$this -> object -> addGlobalProp ($prop);
		$this -> assertTrue (in_array ($prop, $this -> object -> getGlobalProps (), true));
		try
		{
			$this -> object -> addGlobalProp ($prop);
		}
		catch (\Exception $e)
		{
			$exception	= $e;
		}
		$this -> assertInstanceOf ('\InvalidArgumentException', $exception);
	}
	
	/**
	 */
	public function testDeleteGlobalProp ()
	{
		$prop	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Prop');
		$this -> object -> addGlobalProp ($prop);
		$this -> assertTrue (in_array ($prop, $this -> object -> getGlobalProps (), true));
		$this -> object -> deleteGlobalProp (get_class ($prop));
		$this -> assertFalse (in_array ($prop, $this -> object -> getGlobalProps (), true));
	}

	/**
	 */
	public function testGetGlobalProps ()
	{
		$prop1	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Prop', array (), array (), 'TestProp1');
		$prop2	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Prop', array (), array (), 'TestProp2');
		$prop3	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Prop', array (), array (), 'TestProp3');
		
		$props	= array (
			get_class ($prop1)	=> $prop1,
			get_class ($prop2)	=> $prop2,
			get_class ($prop3)	=> $prop3
		);
		
		$this -> object -> addGlobalProp ($prop1) -> addGlobalProp ($prop2) -> addGlobalProp ($prop3);
		
		$this -> assertTrue ($this -> object -> getGlobalProps () === $props);
	}

	/**
	 */
	public function testSetGlobalType ()
	{
		$mock	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Type');
		$this -> object -> setGlobalType ($mock);
		$this -> assertTrue ($mock === $this -> object -> getGlobalType ());
	}

	/**
	 */
	public function testGetGlobalType ()
	{
		$this -> assertNull ($this -> object -> getGlobalType ());
		$mock	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Type');
		$this -> object -> setGlobalType ($mock);
		$this -> assertTrue ($mock === $this -> object -> getGlobalType ());
	}

	/**
	 */
	public function testGetGlobalRules ()
	{
		$type	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Type');
		$prop1	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Prop', array (), array (), 'TestProp4');
		$prop2	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Prop', array (), array (), 'TestProp5');
		$prop3	= $this -> getMock ('\gordian\reefknot\input\validate\iface\Prop', array (), array (), 'TestProp6');
		
		$rules	= array (
			get_class ($type)	=> $type,
			get_class ($prop1)	=> $prop1,
			get_class ($prop2)	=> $prop2,
			get_class ($prop3)	=> $prop3
		);
		
		$this -> object -> setGlobalType ($type) 
						-> addGlobalProp ($prop1) 
						-> addGlobalProp ($prop2) 
						-> addGlobalProp ($prop3);
		
		$this -> assertTrue ($this -> object -> getGlobalRules () === $rules);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testIsValid().
	 */
	public function testIsValid ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}
