<?php

namespace gordian\reefknot\input\validate;

/**
 * Test class for DataSet.
 * Generated by PHPUnit on 2011-12-17 at 18:10:34.
 */
class DataSetTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var gordian\reefknot\input\validate\DataSet
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$arrMock	= $this -> getMock ('\gordian\reefknot\input\validate\type\IsArray');
		$this -> object = new DataSet ($arrMock);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @todo Implement testAddField().
	 */
	public function testAddField ()
	{
		$this -> object -> addField ('testfield', $this -> getMock ('\gordian\reefknot\input\validate\iface\Field'));
		//var_dump ($this -> object -> getFields ());
	}

	/**
	 * @todo Implement testDeleteField().
	 */
	public function testDeleteField ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetFields().
	 */
	public function testGetFields ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetData().
	 */
	public function testSetData ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsValid().
	 */
	public function testIsValid ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}
