<?php

namespace gordian\reefknot\input\validate;

require_once dirname(__FILE__) . '/../../../input/validate/DataSetGlobalized.php';

/**
 * Test class for DataSetGlobalized.
 * Generated by PHPUnit on 2012-03-20 at 15:18:07.
 */
class DataSetGlobalizedTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var DataSetGlobalized
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new DataSetGlobalized;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers gordian\reefknot\input\validate\DataSetGlobalized::addGlobalProp
	 * @todo Implement testAddGlobalProp().
	 */
	public function testAddGlobalProp() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers gordian\reefknot\input\validate\DataSetGlobalized::deleteGlobalProp
	 * @todo Implement testDeleteGlobalProp().
	 */
	public function testDeleteGlobalProp() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers gordian\reefknot\input\validate\DataSetGlobalized::getGlobalProps
	 * @todo Implement testGetGlobalProps().
	 */
	public function testGetGlobalProps() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
