<?php

namespace gordian\reefknot\input\validate;

/**
 * Test class for Field.
 * Generated by PHPUnit on 2011-12-17 at 18:10:34.
 */
class FieldTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var \gordian\reefknot\input\validate\Field
	 */
	protected $object;

	/**
	 * Helper for building mock props
	 * 
	 * @param mixed $value
	 * @param bool $isValid
	 * @return gordian\reefknot\input\validate\iface\Rule
	 */
	protected function makeStub ($type, $value = NULL, $isValid = true)
	{
		$stub	= $this -> getMockBuilder ('gordian\reefknot\input\validate\iface\\' . $type)
				-> disableOriginalConstructor ()
				-> getMock ();
		
		$stub	-> expects ($this -> any ())
				-> method ('setData')
				-> will ($this -> returnValue ($stub));
		
		$stub	-> expects ($this -> any ())
				-> method ('getData')
				-> will ($this -> returnValue ($value));
		
		$stub	-> expects ($this -> any ())
				-> method ('isValid')
				-> will ($this -> returnValue ($isValid));

		return ($stub);
	}
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new Field ($this -> makeStub ('Type'));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}
	
	/**
	 * Test that we can set NULL as the data
	 */
	public function testSetDataNull ()
	{
		$this -> object -> setData (NULL);
		$this -> assertNull ($this -> object -> getData ());
	}
	
	/**
	 * Test that we can set an integer as the data
	 */
	public function testSetDataInt () 
	{
		$this -> object -> setData (123);
		$this -> assertSame ($this -> object -> getData (), 123);
	}
	
	/**
	 * Test that we can set a float as the data
	 */
	public function testSetDataFloat ()
	{
		$this -> object -> setData (pi ());
		$this -> assertSame ($this -> object -> getData (), pi ());
	}
	
	/**
	 * Test that we can set an empty array as the data
	 */
	public function testSetDataEmptyArray ()
	{
		$this -> object -> setData (array ());
		$this -> assertSame ($this -> object -> getData (), array ());
	}
	
	/**
	 * Test that we can set an indexed array as the data
	 */
	public function testSetDataIndexedArray ()
	{
		$this -> object -> setData (array (1, 2, 3));
		$this -> assertSame ($this -> object -> getData (), array (1, 2, 3));
	}
	
	/**
	 * Test that we can set an associative array as the data
	 */
	public function testSetDataAssocArray ()
	{
		$this -> object -> setData (array ('foo' => 1, 'bar' => 2, 'baz' => 3));
		$this -> assertSame ($this -> object -> getData (), array ('foo' => 1, 'bar' => 2, 'baz' => 3));
	}
	
	/**
	 * Test that setData works when there are props defined
	 */
	public function testSetDataWithFields ()
	{
		$this -> object -> addProp ($this -> makeStub ('Prop'))
						-> addProp ($this -> makeStub ('Prop'))
						-> addProp ($this -> makeStub ('Prop'))
						-> setData (NULL);
		
		$this -> assertNull ($this -> object -> getData ());
		$this -> object -> setData (123);
		$this -> assertSame ($this -> object -> getData (), 123);
		$this -> object -> setData (pi ());
		$this -> assertSame ($this -> object -> getData (), pi ());
		$this -> object -> setData (array ());
		$this -> assertSame ($this -> object -> getData (), array ());
		$this -> object -> setData (array (1, 2, 3));
		$this -> assertSame ($this -> object -> getData (), array (1, 2, 3));
		$this -> object -> setData (array ('foo' => 1, 'bar' => 2, 'baz' => 3));
		$this -> assertSame ($this -> object -> getData (), array ('foo' => 1, 'bar' => 2, 'baz' => 3));
	}
	
	/**
	 * Test that we can validate
	 */
	public function testIsValidPasses ()
	{
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * test that if all props say that the data is valid then a valid response is returned
	 */
	public function testIsValidWithPropsPasses ()
	{
		$this -> object -> addProp ($this -> makeStub ('Prop'))
						-> addProp ($this -> makeStub ('Prop'))
						-> addProp ($this -> makeStub ('Prop'));
		
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * Test that an invalid type causes validation to fail
	 */
	public function testIsValidFails ()
	{
		$this -> object -> setType ($this -> makeStub ('Type', NULL, false));
		
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	/**
	 * Test that invalid props cause validation to fail
	 */
	public function testIsValidWithPropsFails ()
	{
		$this -> object -> addProp ($this -> makeStub ('Prop', NULL, false))
						-> addProp ($this -> makeStub ('Prop', NULL, false))
						-> addProp ($this -> makeStub ('Prop', NULL, false));
		
		$this -> assertFalse ($this -> object -> isValid ());
	}
}
