<?php

namespace gordian\reefknot\input\validate;

require_once dirname (__FILE__) . '/../../../input/validate/Group.php';

/**
 * Test class for Group.
 * Generated by PHPUnit on 2012-01-21 at 18:05:09.
 */
class GroupTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Group
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new Group;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testIsValid().
	 */
	public function testIsValid ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}

?>
