<?php

namespace gordian\reefknot\input\validate\prop;

require_once dirname (__FILE__) . '/../../../../input/validate/prop/Max.php';

/**
 * Test class for Max.
 * Generated by PHPUnit on 2011-12-11 at 10:22:57.
 */
class MinTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Max
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new Min (array ('limit' => 5));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}
	
	public function testIsValidNullPasses ()
	{
		$this -> object -> setData (NULL);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidIntPasses ()
	{
		$this -> object -> setData (42);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidFloatPasses ()
	{
		$this -> object -> setData (pi () * 2);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidStringPasses ()
	{
		$this -> object -> setData ('The quick brown fox jumps over the lazy dog');
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidArrayPasses ()
	{
		$this -> object -> setData (array (1, 2, 3, 4, 5, 6));
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidAssocPasses ()
	{
		$this -> object -> setData (array ('a' => 1, 'b' => 2, 'c' => 3, 'd' => 4, 'e' => 5, 'f' => 6));
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidIntEdgePasses ()
	{
		$this -> object -> setData (5);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidFloatEdgePasses ()
	{
		$this -> object -> setData (5.0);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidStringEdgePasses ()
	{
		$this -> object -> setData ('Fifth');
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidArrayEdgePasses ()
	{
		$this -> object -> setData (array (1, 2, 3, 4, 5));
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidAssocEdgePasses ()
	{
		$this -> object -> setData (array ('a' => 1, 'b' => 2, 'c' => 3, 'd' => 4, 'e' => 5));
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidIntUnderFails ()
	{
		$this -> object -> setData (4);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidFloatUnderFails ()
	{
		$this -> object -> setData (4.9999);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidStringOverFails ()
	{
		$this -> object -> setData ('fail');
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidArrayOverFails ()
	{
		$this -> object -> setData (array (1, 2, 3, 4));
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidAssocOverFails ()
	{
		$this -> object -> setData (array ('a' => 1, 'b' => 2, 'c' => 3, 'd' => 4));
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidWrongTypeThrowsException ()
	{
		$exception	= NULL;
		$this -> object -> setData (true);
		try 
		{
			$this -> object -> isValid ();
		}
		catch (\Exception $e)
		{
			$exception	= $e;
		}
		$this -> assertTrue ($exception instanceof \InvalidArgumentException);
	}
	
	public function testIsValidIntFromFieldPasses ()
	{
		$field		= $this	-> getMockBuilder ('gordian\reefknot\input\validate\Field')
							-> disableOriginalConstructor ()
							-> getMock ();
		
		$field	-> expects ($this -> any ())
				-> method ('isValid')
				-> will ($this -> returnValue (true));
		
		$field	-> expects ($this -> any ())
				-> method ('getData')
				-> will ($this -> returnValue (10));
		
		$this -> object	-> setConfig (array ('limit' => $field))
						-> setData (11);
		
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidIntFromFieldFails ()
	{
		$field		= $this	-> getMockBuilder ('gordian\reefknot\input\validate\Field')
							-> disableOriginalConstructor ()
							-> getMock ();
		
		$field	-> expects ($this -> any ())
				-> method ('isValid')
				-> will ($this -> returnValue (true));
		
		$field	-> expects ($this -> any ())
				-> method ('getData')
				-> will ($this -> returnValue (10));
		
		$this -> object	-> setConfig (array ('limit' => $field))
						-> setData (9);
		
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidIntFromInvalidFieldFails ()
	{
		$field		= $this	-> getMockBuilder ('gordian\reefknot\input\validate\Field')
							-> disableOriginalConstructor ()
							-> getMock ();
		
		$field	-> expects ($this -> any ())
				-> method ('isValid')
				-> will ($this -> returnValue (false));
		
		$field	-> expects ($this -> any ())
				-> method ('getData')
				-> will ($this -> returnValue (10));
		
		$this -> object	-> setConfig (array ('limit' => $field))
						-> setData (11);
		
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidIntFromNonNumericFieldFails ()
	{
		$field		= $this	-> getMockBuilder ('gordian\reefknot\input\validate\Field')
							-> disableOriginalConstructor ()
							-> getMock ();
		
		$field	-> expects ($this -> any ())
				-> method ('isValid')
				-> will ($this -> returnValue (true));
		
		$field	-> expects ($this -> any ())
				-> method ('getData')
				-> will ($this -> returnValue ('asdf'));
		
		$this -> object	-> setConfig (array ('limit' => $field))
						-> setData (11);
		
		$this -> assertFalse ($this -> object -> isValid ());
	}
}
