<?php

namespace gordian\reefknot\input\validate\prop;

use gordian\reefknot\input\validate\iface;

/**
 * Test class for RequiredOnVal.
 * Generated by PHPUnit on 2012-01-27 at 08:32:53.
 */
class RequiredOnValTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var gordian\reefknot\input\validate\prop\RequiredOnVal
	 */
	protected $object;

	/**
	 * Helper for building validatables
	 * 
	 * @param mixed $value
	 * @param bool $isValid
	 * @return gordian\reefknot\input\validate\Field 
	 */
	protected function makeStubField ($value = NULL, $isValid = true)
	{
		$stubField	= $this	-> getMockBuilder ('gordian\reefknot\input\validate\iface\Validatable')
							-> disableOriginalConstructor ()
							-> getMock ();
		
		$stubField			-> expects ($this -> any ()) 
							-> method ('isValid')
							-> will ($this -> returnValue ($isValid));
		
		$stubField		 	-> expects ($this -> any ()) 
							-> method ('getData')
							-> will ($this -> returnValue ($value));
		
		return ($stubField);
	}
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new RequiredOnVal (array (
			'dependant'			=> 0, 
			'requireWhenEmpty'	=> true
		));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}
	
	public function testSetConfigValidPasses ()
	{
		$cfg	= array (
			'dependant'			=> NULL, 
			'requireWhenEmpty'	=> true
		);
	}
	
	/**
	 * If our data is required when the dependant is empty and the dependant is
	 * empty, then our data should not pass validation if it doesn't have a 
	 * value. 
	 */
	public function testIsValid1 ()
	{
		$cfg	= array ('dependant' => NULL, 'requireWhenEmpty' => true);
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is empty and the dependant is
	 * empty, then our data should pass validation if it has a value. 
	 */
	public function testIsValid2 ()
	{
		$cfg	= array ('dependant' => NULL, 'requireWhenEmpty' => true);
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is empty and the dependant is
	 * not empty, then our data should pass validation if it doesn't have a 
	 * value.
	 */
	public function testIsValid3 ()
	{
		$cfg	= array ('dependant' => 123, 'requireWhenEmpty' => true);
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is empty and the dependant is
	 * not empty, then our data should pass validation if it has a value.
	 */
	public function testIsValid4 ()
	{
		$cfg	= array ('dependant' => 123, 'requireWhenEmpty' => true);
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is not empty and the dependant
	 * is empty, our data should pass validation if it doesn't have a value. 
	 */
	public function testIsValid5 ()
	{
		$cfg	= array ('dependant' => NULL, 'requireWhenEmpty' => false);
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is not empty and the dependant
	 * is empty, our data should pass validation if it has a value. 
	 */
	public function testIsValid6 ()
	{
		$cfg	= array ('dependant' => NULL, 'requireWhenEmpty' => false);
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is not empty and the dependant
	 * is not empty, our data should not pass validation if it doesn't have a
	 * value. 
	 */
	public function testIsValid7 ()
	{
		$cfg	= array ('dependant' => 123, 'requireWhenEmpty' => false);
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is not empty and the dependant
	 * is not empty, our data should pass validation if it has a value. 
	 */
	public function testIsValid8 ()
	{
		$cfg	= array ('dependant' => 123, 'requireWhenEmpty' => true);
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is empty and the dependant is
	 * empty, then our data should not pass validation if it doesn't have a 
	 * value. 
	 */
	public function testIsValidAgainstValidatable1 ()
	{
		$dep	= $this -> makeStubField (NULL, true);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => true);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is empty and the dependant is
	 * empty, then our data should pass validation if it has a value. 
	 */
	public function testIsValidAgainstValidatable2 ()
	{
		$dep	= $this -> makeStubField (NULL, true);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => true);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is empty and the dependant is
	 * not empty, then our data should pass validation if it doesn't have a 
	 * value.
	 */
	public function testIsValidAgainstValidatable3 ()
	{
		$dep	= $this -> makeStubField (123, true);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => true);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is empty, and the dependant is
	 * not empty, then our data should pass validation if it has a value.
	 */
	public function testIsValidAgainstValidatable4 ()
	{
		$dep	= $this -> makeStubField (123, true);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => true);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is not empty and the dependant
	 * is empty, our data should pass validation if it doesn't have a value. 
	 */
	public function testIsValidAgainstValidatable5 ()
	{
		$dep	= $this -> makeStubField (NULL, true);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => false);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is not empty and the dependant
	 * is empty, our data should pass validation if it has a value. 
	 */
	public function testIsValidAgainstValidatable6 ()
	{
		$dep	= $this -> makeStubField (NULL, true);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => false);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is not empty and the dependant
	 * is not empty, our data should not pass validation if it doesn't have a
	 * value. 
	 */
	public function testIsValidAgainstValidatable7 ()
	{
		$dep	= $this -> makeStubField (123, true);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => false);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	/**
	 * If our data is required when the dependant is not empty and the dependant
	 * is not empty, our data should pass validation if it has a value. 
	 */
	public function testIsValidAgainstValidatable8 ()
	{
		$dep	= $this -> makeStubField (123, true);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => false);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidAgainstInvalidFail1 ()
	{
		$dep	= $this -> makeStubField (NULL, false);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => true);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidAgainstInvalidFail2 ()
	{
		$dep	= $this -> makeStubField (NULL, false);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => true);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidAgainstInvalidFail3 ()
	{
		$dep	= $this -> makeStubField (NULL, false);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => false);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (NULL);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidAgainstInvalidFail4 ()
	{
		$dep	= $this -> makeStubField (NULL, false);
		$cfg	= array ('dependant' => $dep, 'requireWhenEmpty' => false);
		
		$this -> object	-> setConfig ($cfg)
						-> setData (12345);
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	
	/**
	 * Test that trying to configure with no data triggers an InvalidArgumentException
	 */
	public function testSetConfigEmptyThrowsException ()
	{
		$cfg		= array ();
		$exception	= NULL;
		try
		{
			$this -> object -> setConfig ($cfg);
		}
		catch (\Exception $e)
		{
			$exception	= $e;
		}
		$this -> assertInstanceOf ('\InvalidArgumentException', $exception);
		$this -> assertFalse ($this -> object -> getConfig () === $cfg);
	}
	
	/**
	 * Test that trying to configure with no prop data triggers an InvalidArgumentException 
	 */
	public function testSetConfigNoPropsThrowsException ()
	{
		$cfg		= array ('foo' => 'bar');
		$exception	= NULL;
		try
		{
			$this -> object -> setConfig ($cfg);
		}
		catch (\Exception $e)
		{
			$exception	= $e;
		}
		$this -> assertInstanceOf ('\InvalidArgumentException', $exception);
		$this -> assertFalse ($this -> object -> getConfig () === $cfg);
	}
	
	/**
	 * Test that valid needles can be passed to the object 
	 */
	public function testSetConfigPasses ()
	{
		$cfg		= array ('dependant' => 12321, 'requireWhenEmpty' => false);
		$exception	= NULL;
		try
		{
			$this -> object -> setConfig ($cfg);
		}
		catch (\Exception $e)
		{
			$exception	= $e;
		}
		$this -> assertNull ($exception);
		$this -> assertTrue ($this -> object -> getConfig () === $cfg);
	}
	
	public function testSetConfigPasses2 ()
	{
		$cfg		= array ('dependant' => $this -> makeStubField ('123', true), 'requireWhenEmpty' => false);
		$exception	= NULL;
		try
		{
			$this -> object -> setConfig ($cfg);
		}
		catch (\Exception $e)
		{
			$exception	= $e;
		}
		$this -> assertNull ($exception);
		$this -> assertTrue ($this -> object -> getConfig () === $cfg);
	}
}
