<?php

namespace gordian\reefknot\input\validate\prop;

/**
 * Test class for SetMember.
 * Generated by PHPUnit on 2011-12-15 at 21:25:23.
 */
class SetMemberTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var gordian\reefknot\input\validate\prop\SetMember
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new SetMember (array ('set' => array (1, 2, 4, 8)));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * Test that a null value passes validation 
	 */
	public function testIsValidNullPasses ()
	{
		$this -> object -> setData (NULL);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidInSetPasses ()
	{
		$this -> object -> setData (4);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValisNotInSetFails ()
	{
		$this -> object -> setData (3);
		$this -> assertFalse ($this -> object -> isValid ());
	}
}
