<?php

namespace gordian\reefknot\input\validate\prop;

/**
 * Test class for Subset.
 * Generated by PHPUnit on 2012-01-14 at 10:02:50.
 */
class SubsetTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var gordian\reefknot\input\validate\prop\Subset
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new Subset (array ('set' => array (1, 2, 4, 8)));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * Test that a null value passes validation 
	 */
	public function testIsValidNullPasses ()
	{
		$this -> object -> setData (NULL);
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidEmptyArrayPasses ()
	{
		$this -> object -> setData (array ());
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidSameArrayPasses ()
	{
		$this -> object -> setData (array (1, 2, 4, 8));
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidSubsetPasses ()
	{
		$this -> object -> setData (array (2, 8));
		$this -> assertTrue ($this -> object -> isValid ());
	}
	
	public function testIsValidPartialSubsetFails ()
	{
		$this -> object -> setData (array (1, 2, 3, 4));
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidNoSubsetFails ()
	{
		$this -> object -> setData (array (11, 22, 44, 88));
		$this -> assertFalse ($this -> object -> isValid ());
	}
	
	public function testIsValidNotArrayThrowsException ()
	{
		$this -> object -> setData ('Test');
		$exception	= NULL;
		$valid		= NULL;
		
		try
		{
			$valid	= $this -> object -> isValid ();
		}
		catch (\Exception $e)
		{
			$exception	= $e;
		}
		
		$this -> assertTrue ($exception instanceof \InvalidArgumentException);
		$this -> assertNull ($valid);
	}
}
