<?php

namespace gordian\reefknot\access;

require_once dirname (__FILE__) . '/../../access/Level.php';

/**
 * Test class for Level.
 * Generated by PHPUnit on 2012-03-27 at 17:43:00.
 */
class LevelTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Level
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new Level;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

}

?>
