<?php

namespace gordian\reefknot\access;

require_once dirname (__FILE__) . '/../../access/Rbac.php';

/**
 * Test class for Rbac.
 * Generated by PHPUnit on 2012-03-27 at 17:42:59.
 */
class RbacTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Rbac
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new Rbac;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

}

?>
