<?php

namespace gordian\reefknot\input\validate\abstr\prop;

/**
 * Test class for Logic.
 * Generated by PHPUnit on 2012-01-21 at 18:05:12.
 */
class LogicTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Logic
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new Logic;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

}
