<?php

namespace gordian\reefknot\input\validate\abstr\prop;

require_once dirname (__FILE__) . '/../../../../../input/validate/abstr/prop/TextMatch.php';

/**
 * Test class for TextMatch.
 * Generated by PHPUnit on 2012-03-27 at 17:43:05.
 */
class TextMatchTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var TextMatch
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		//$this -> object = new TextMatch;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testSetConfig().
	 */
	public function testSetConfig ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}

?>
