<?php

namespace gordian\reefknot\access\abstr;

require_once dirname (__FILE__) . '/../../../access/abstr/Access.php';

/**
 * Test class for Access.
 * Generated by PHPUnit on 2012-03-27 at 17:43:01.
 */
class AccessTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Access
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new Access;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

}

?>
