<?php

namespace gordian\reefknot\autoload;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-15 at 12:41:45.
 */
class MappedAutoloaderTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var MappedAutoloader
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new MappedAutoloader (__DIR__ . '/exampleclasses', 'gordian\exampleclasses');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @covers gordian\reefknot\autoload\MappedAutoloader::getClassMap
	 * @todo   Implement testGetClassMap().
	 */
	public function testGetClassMap ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers gordian\reefknot\autoload\MappedAutoloader::setClassMap
	 * @todo   Implement testSetClassMap().
	 */
	public function testSetClassMap ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers gordian\reefknot\autoload\MappedAutoloader::enableAutoPopulate
	 * @todo   Implement testEnableAutoPopulate().
	 */
	public function testEnableAutoPopulate ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers gordian\reefknot\autoload\MappedAutoloader::disableAutoPopulate
	 * @todo   Implement testDisableAutoPopulate().
	 */
	public function testDisableAutoPopulate ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers gordian\reefknot\autoload\MappedAutoloader::isAutoPopulateEnabled
	 * @todo   Implement testIsAutoPopulateEnabled().
	 */
	public function testIsAutoPopulateEnabled ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}
