<?php

namespace gordian\reefknot\input\filter;

require_once dirname (__FILE__) . '/../../../input/filter/MagicQuotes.php';

/**
 * Test class for MagicQuotes.
 * Generated by PHPUnit on 2012-03-27 at 17:43:01.
 */
class MagicQuotesTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var MagicQuotes
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new MagicQuotes;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testFilter().
	 */
	public function testFilter ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}

?>
