<?php

namespace gordian\reefknot\input\validate\abstr;

require_once dirname (__FILE__) . '/../../../../input/validate/abstr/Node.php';

/**
 * Test class for Node.
 * Generated by PHPUnit on 2011-12-17 at 18:10:34.
 */
class NodeTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Node
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		//$this -> object = $this -> getMockForAbstractClass ('gordian\reefknot\input\validate\abstr\Node');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testAddProp().
	 */
	public function testAddProp ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testDeleteProp().
	 */
	public function testDeleteProp ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testGetProps().
	 */
	public function testGetProps ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testSetType().
	 */
	public function testSetType ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testGetType().
	 */
	public function testGetType ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}

?>
