<?php

namespace gordian\reefknot\input\validate\abstr;

/**
 * Test class for Prop.
 * Generated by PHPUnit on 2011-12-17 at 18:10:35.
 */
class PropTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var \gordian\reefknot\input\validate\abstr\Prop
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = $this -> getMockForAbstractClass ('gordian\reefknot\input\validate\abstr\Prop', array (array ('mockkey' => 'mockvalue')));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * Test that we can set the configuration
	 */
	public function testSetConfig ()
	{
		$this -> object -> setConfig (array ());
		$this -> assertSame ($this -> object -> getConfig (), array ());
		$this -> object -> setConfig (array ('foo' => 'bar', 'baz' => 'quux'));
		$this -> assertSame ($this -> object -> getConfig (), array ('foo' => 'bar', 'baz' => 'quux'));
	}

	/**
	 * Test that we can get the configuration
	 */
	public function testGetConfig ()
	{
		$this -> assertSame ($this -> object -> getConfig (), array ('mockkey' => 'mockvalue'));
	}
}
