<?php

namespace gordian\reefknot\input\validate\abstr;

require_once dirname (__FILE__) . '/../../../../input/validate/abstr/Validatable.php';

/**
 * Test class for Validatable.
 * Generated by PHPUnit on 2011-12-17 at 18:10:35.
 */
class ValidatableTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Validatable
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = $this -> getMockForAbstractClass ('gordian\reefknot\input\validate\abstr\Validatable');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testSetData().
	 */
	public function testSetData ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testGetData().
	 */
	public function testGetData ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}

?>
