<?php

namespace gordian\reefknot\input\filter\abstr;

require_once dirname (__FILE__) . '/../../../../input/filter/abstr/Filter.php';

/**
 * Test class for Filter.
 * Generated by PHPUnit on 2012-03-27 at 17:43:03.
 */
class FilterTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Filter
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		//$this -> object = new Filter;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testSetData().
	 */
	public function testSetData ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testSetConfig().
	 */
	public function testSetConfig ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testGetConfig().
	 */
	public function testGetConfig ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}

?>
