<?php

namespace gordian\reefknot\autoload\classmap;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-03 at 16:40:57.
 */
class ArrayClassMapTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var ArrayClassMap
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp ()
	{
		$this -> object = new ArrayClassMap;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}
	
	public function testConstruct () {
		$expected	= array (
			'TestClass1'	=> '/test/path/TestClass1.php',
			'TestClass2'	=> '/test/path/TestClass2.php',
			'TestClass3'	=> '/test/path/TestClass3.php'
		);
		
		$this -> object	= new ArrayClassMap ($expected);
		
		$this -> assertEmpty (array_diff_assoc ($expected, $this -> object -> getAll ()));
		$this -> assertEmpty (array_diff_assoc ($this -> object -> getAll (), $expected));
	}
}
