<?php

namespace gordian\reefknot\autoload\classmap;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-15 at 12:42:11.
 * 
 * @requires extension yaml
 */
class YamlFileClassMapTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var YamlFileClassMap
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 * 
	 * @requires extension yaml
	 */
	protected function setUp ()
	{
		//$this -> object = new YamlFileClassMap;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown ()
	{
		
	}

	/**
	 * @covers gordian\reefknot\autoload\classmap\YamlFileClassMap::load
	 * @todo   Implement testLoad().
	 * @requires extension yaml
	 */
	public function testLoad ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers gordian\reefknot\autoload\classmap\YamlFileClassMap::save
	 * @todo   Implement testSave().
	 * @requires extension yaml
	 */
	public function testSave ()
	{
		// Remove the following lines when you implement this test.
		$this -> markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}

}
